field: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
fieldLayouts:
  f3caeaf8-c441-4ad3-a2e8-5ea9abdc3340:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b507c631-830f-46d6-b625-4d4a6df7775c # Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eab65f53-ddcc-4fe7-86a6-125f0da1b7b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80c3b02f-d4d4-4fb2-8c5c-1cde8119afad # Section Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bbe1188-9327-49e7-a774-9a8025b4a074
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77af2e3b-d586-4daa-b99c-fd4792c204da # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f199898-3c5d-4edc-bc9c-8140c1e08e8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7f94964-43d2-4526-914c-0aab192f6b93
        userCondition: null
fields:
  77af2e3b-d586-4daa-b99c-fd4792c204da: # Copy
    columnSuffix: oywabdij
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes:
        - 70f5d47b-4830-4d51-95fe-bc0f7ccc0670 # Uploads
      ckeConfig: 12f17257-6f1c-4e4c-837e-17ad76241a60 # Site
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
  80c3b02f-d4d4-4fb2-8c5c-1cde8119afad: # Section Title
    columnSuffix: rqrvhxtc
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: null
    name: 'Section Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b507c631-830f-46d6-b625-4d4a6df7775c: # Padding
    columnSuffix: rdhahobp
    contentColumnType: string
    fieldGroup: null
    handle: padding
    instructions: null
    name: Padding
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Top & Bottom'
            -
              - value
              - section-y-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Top Only'
            -
              - value
              - section-t-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Bottom Only'
            -
              - value
              - section-b-padding
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'No Padding'
            -
              - value
              - section-no-padding
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: copy
name: Copy
sortOrder: 1
