field: ab8abc7e-2a4d-4858-98ea-9a6954a434da # Hero
fieldLayouts:
  532fe5e4-df32-4a3a-a746-e5f91f6e168b:
    tabs:
      -
        elements:
          -
            fieldUid: 8c583e9a-a56d-486d-8550-e7eae61c8088 # Slides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61e062bf-9716-4fe4-892c-bc2dadb71721
            warning: null
            width: 100
        name: Content
        uid: e0366ccf-37de-4a01-9c00-95a40acd04f2
fields:
  8c583e9a-a56d-486d-8550-e7eae61c8088: # Slides
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slides
    instructions: null
    name: Slides
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - d5f8da04-ca55-4c9f-8605-e7f8779e82b8 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 01313804-5d1a-410f-9da8-42ea30ae231d # Slide Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 8491df26-ac74-440e-8ce9-403654b8ce98 # Copy
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 59621bb5-03e8-481a-b377-5e08b5a79c12 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_slides}}'
      fieldLayout: row
      maxRows: 5
      minRows: 1
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: sliderHero
name: 'Slider Hero'
sortOrder: 2
