field: ab8abc7e-2a4d-4858-98ea-9a6954a434da # Hero
fieldLayouts:
  73281f26-73de-4318-a067-3d6c6905b1cd:
    tabs:
      -
        elements:
          -
            fieldUid: 7bf7da79-8f7d-4a1b-8129-121b24c0d99b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98f0e07e-81da-484f-8190-987af0f739c8
            warning: null
            width: 100
          -
            fieldUid: 21077893-9405-4330-ba61-9f695515c9fb # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 360e355c-d9f2-417d-af9f-ce89b15c6e4a
            warning: null
            width: 100
          -
            fieldUid: da3d7ec4-1d85-47ba-a517-6c81d94cc9d2 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b95dfd47-bd17-4d2d-b2f5-586a0750667f
            warning: null
            width: 100
          -
            fieldUid: 4d4435a9-cff2-46e6-9e43-ca2b7d62486f # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f7852fc-9a4e-40a7-9816-dbb286775bf9
            warning: null
            width: 100
        name: Content
        uid: 4f2e4fad-7ce3-4757-abbd-6483c2dc8abe
fields:
  4d4435a9-cff2-46e6-9e43-ca2b7d62486f: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: true
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  7bf7da79-8f7d-4a1b-8129-121b24c0d99b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: true
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      restrictedLocationSubpath: hero
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  21077893-9405-4330-ba61-9f695515c9fb: # Hero Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heroTitle
    instructions: 'If empty page title will be used'
    name: 'Hero Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  da3d7ec4-1d85-47ba-a517-6c81d94cc9d2: # Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 3e09420e-30db-49dd-9520-4775f6667303 # Site Basic
      columnType: text
      defaultTransform: ''
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
handle: standardHero
name: 'Standard Hero'
sortOrder: 1
