field: d974bf8d-647d-45f3-98be-0733d5e3e1ba # User Guide
fieldLayouts:
  2be8891e-b97f-4d20-8c96-63ee3acef638:
    tabs:
      -
        elements:
          -
            fieldUid: 14e1bd82-34c0-42c5-a72d-1d002d9775d2 # Video Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 344c64f5-781b-4fb5-a46b-4429b9f2f253
            warning: null
            width: 100
          -
            fieldUid: 158c7930-10bb-483f-8328-c8aa657d8647 # Video ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d461c76-9beb-40da-ae5e-a9d0fe2ded2d
            warning: null
            width: 100
        name: Content
        uid: 22553107-05a0-4b71-be18-0d3a3d8035b8
fields:
  14e1bd82-34c0-42c5-a72d-1d002d9775d2: # Video Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoTitle
    instructions: null
    name: 'Video Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  158c7930-10bb-483f-8328-c8aa657d8647: # Video ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoId
    instructions: 'i.e. LTRD2wUQ4KY'
    name: 'Video ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: youtubeVideo
name: 'YouTube Video'
sortOrder: 4
