color: null
fieldLayouts:
  dc49b215-dcb8-4177-9ecd-36ece2b038a7:
    cardView:
      - 'layoutElement:2d611c9f-ce5d-4fb3-89b7-6cbbac684b4a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T11:45:28-05:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: heroTitle
            instructions: 'If empty page title will be used'
            label: 'Hero Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d611c9f-ce5d-4fb3-89b7-6cbbac684b4a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eaada003-5ead-470a-9054-8417d845e9be
        userCondition: null
handle: basicHero
hasTitleField: false
icon: null
name: 'Basic Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
