color: null
fieldLayouts:
  7d8c40f9-257c-41b4-8747-551f180cacc5:
    cardView:
      - 'layoutElement:1b392e2e-ab1b-42ce-81a1-01fbd59e5ce6'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-10T13:55:01+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionTitle
            instructions: null
            label: 'Section Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a71662d0-b947-40fe-9aee-693197d4445b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T14:14:10+00:00'
            elementCondition: null
            heading: Button
            type: craft\fieldlayoutelements\Heading
            uid: 4d3c66b5-b450-43b5-9c31-784ca651934b
            userCondition: null
          -
            dateAdded: '2024-08-10T13:55:01+00:00'
            elementCondition: null
            fieldUid: 136d3c61-5e7c-4eb4-afc0-5c78565fbe8b # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdb7e4c4-caa6-40d1-bb93-831a931266f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T13:57:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c9c6d83f-3770-4b0a-8802-e2a8d180b708
            userCondition: null
          -
            dateAdded: '2024-08-10T13:55:01+00:00'
            elementCondition: null
            fieldUid: cc618569-5c0e-4ff7-9b4a-2fe9ed27af1f # Background Image
            handle: null
            instructions: null
            label: 'Background Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c36cc61-1f7c-4373-91f1-16aa37ce2c5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d76b4b4a-101d-4508-8153-84c7205cd9a3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-10T13:55:01+00:00'
            elementCondition: null
            fieldUid: 127f0d67-cfaf-4e5d-b3f8-111b7fda6f64 # Padding
            handle: null
            instructions: null
            label: Padding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b392e2e-ab1b-42ce-81a1-01fbd59e5ce6
            userCondition: null
            warning: null
            width: 100
        name: Options
        uid: 20860368-2cde-47b2-8a45-468b6f3b4fc0
        userCondition: null
    thumbFieldKey: 'layoutElement:4c36cc61-1f7c-4373-91f1-16aa37ce2c5b'
handle: callToAction
hasTitleField: false
icon: link
name: 'Call To Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
