fieldLayouts:
  171a213e-9b33-49e7-bf1d-8056ef4d5c12:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 514527a7-c517-4adb-9d54-efdb1f6be1b0
            warning: null
            width: 100
          -
            style: tip
            tip: 'Summary should only be 2-3 sentences. Image will appear on listing page'
            type: craft\fieldlayoutelements\Tip
            uid: f4aec492-bb0f-40b0-afbf-79a590fca8be
          -
            fieldUid: b2f53aa5-81a3-466c-af2d-e30dab4ed3d8 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23da011a-390b-4e37-89a2-4b97651ed706
            warning: null
            width: 50
          -
            fieldUid: 95ce0179-ac46-4ecb-910c-aa91c7a07961 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef618f6-08b3-4fcc-a915-60ee481fb8dd
            warning: null
            width: 50
          -
            fieldUid: fbdde691-0df2-4e8e-b1a8-61a1f555fd0e # News Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbaff3bd-2fb9-4f11-a784-51688db844d5
            warning: null
            width: 100
          -
            heading: 'Main Content'
            type: craft\fieldlayoutelements\Heading
            uid: d7089c82-6c41-4d83-846b-4bafe2301bac
        name: Content
        uid: daf8662e-c051-40ce-9a9f-055743873cb4
      -
        elements:
          -
            fieldUid: 149ec41c-d6de-4ae5-84db-08d285801dd1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8a6d8cd-2973-4ae5-a913-4014dabf5dab
            warning: null
            width: 100
        name: SEO
        uid: a5bc70bc-debf-4ef0-bf9f-162f96619557
handle: default
hasTitleField: true
name: Default
section: 9c12e5ad-18e9-498f-bf50-489513409007 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
