fieldLayouts:
  ff6710b6-fa56-44b7-a693-664ee41ba595:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-27T12:01:38-05:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d1826e4c-3c13-4edf-9d62-56e4d744a3dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T12:01:38-05:00'
            elementCondition: null
            fieldUid: da3d7ec4-1d85-47ba-a517-6c81d94cc9d2 # Copy Basic
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5b39377-f0b4-4435-99cb-6f3e7418b632
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1bdacb6a-18e5-4d7a-ad23-7b647073d35e
        userCondition: null
handle: error404
hasTitleField: true
name: 'Error 404'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
