color: pink
fieldLayouts:
  27773fbe-4706-4cf6-aff2-7c6d13d64fe2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 15c4e0af-8e95-42fa-8015-e4b4a34c0c9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a5d1b5b-fdc1-4395-b5ec-88613d00ba33
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 683d16fd-4d8f-4461-a6dd-15b7ece55232
        userCondition: null
handle: fragments
hasTitleField: true
icon: puzzle-piece
name: Fragments
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
