fieldLayouts:
  27773fbe-4706-4cf6-aff2-7c6d13d64fe2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 15c4e0af-8e95-42fa-8015-e4b4a34c0c9e
            warning: null
            width: 100
          -
            fieldUid: 77af5a62-d057-494a-91ac-9edf65b6b266 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a5d1b5b-fdc1-4395-b5ec-88613d00ba33
            warning: null
            width: 100
        name: Content
        uid: 683d16fd-4d8f-4461-a6dd-15b7ece55232
handle: fragments
hasTitleField: true
name: fragments
section: ce27286a-7635-4494-9c9c-77f2d73352f4 # Fragments
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
