fieldLayouts:
  051e5080-5716-48d1-8d3d-69b3d850a9ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-27T12:01:38-05:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a112464c-3177-4fb9-9327-e01f6f402c5e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T12:01:38-05:00'
            elementCondition: null
            fieldUid: 5489ed3b-28c1-4a26-ac7e-97b0182e6652 # Enable Notice Bar
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a3a9669-fd06-48a0-9c6c-7d57a8673df6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-01-27T12:01:38-05:00'
            elementCondition: null
            fieldUid: 52f12f1b-ba11-48f3-985d-0ee6e2a6dc4e # Notice Bar Location
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73f65df1-43ec-4557-8579-cb72ea2554fc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-01-27T12:01:38-05:00'
            elementCondition: null
            fieldUid: 136d3c61-5e7c-4eb4-afc0-5c78565fbe8b # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af7d8040-e45a-4132-86a1-9020152c0d10
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-01-27T12:01:38-05:00'
            elementCondition: null
            fieldUid: da3d7ec4-1d85-47ba-a517-6c81d94cc9d2 # Copy Basic
            handle: text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1af21084-1c75-4add-af7b-4d5443ae4120
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4678e52f-c995-4149-922a-e84c2d8eb686
        userCondition: null
handle: noticeBar
hasTitleField: false
name: 'Notice Bar'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
