color: null
fieldLayouts:
  5dd65675-497a-4ca9-b807-7e443b915ef5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-27T16:37:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 13a4007c-1fdb-4747-bb47-e83ca4ca29a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:37:49+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionTitle
            instructions: null
            label: 'Section Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52b9bea1-445b-41fa-ac5f-b334fc72f044
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:37:49+00:00'
            elementCondition: null
            fieldUid: 5026b221-a48f-4868-9f48-07428068e77e # Related Entries
            handle: null
            instructions: null
            label: 'Related Entries'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23c2f709-04c7-4f0f-926d-c0f2e04b3fc7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f27ce87-60b4-40a1-8b87-dea3e269f9a5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:37:49+00:00'
            elementCondition: null
            fieldUid: 127f0d67-cfaf-4e5d-b3f8-111b7fda6f64 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5fecab2-6bd5-43f3-9ae5-597561792f6f
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 38096454-3d05-4faf-a7c4-290e1628e1de
        userCondition: null
handle: relatedEntries
hasTitleField: false
icon: ''
name: 'Related Entries'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
