color: null
fieldLayouts:
  73281f26-73de-4318-a067-3d6c6905b1cd:
    cardView:
      - 'layoutElement:360e355c-d9f2-417d-af9f-ce89b15c6e4a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:37:38+00:00'
            elementCondition: null
            fieldUid: 7bf7da79-8f7d-4a1b-8129-121b24c0d99b # Hero Image
            handle: image
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98f0e07e-81da-484f-8190-987af0f739c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:37:38+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: heroTitle
            instructions: 'If empty page title will be used'
            label: 'Hero Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 360e355c-d9f2-417d-af9f-ce89b15c6e4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:37:38+00:00'
            elementCondition: null
            fieldUid: da3d7ec4-1d85-47ba-a517-6c81d94cc9d2 # Copy Basic
            handle: copy
            instructions: null
            label: Copy
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b95dfd47-bd17-4d2d-b2f5-586a0750667f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:37:38+00:00'
            elementCondition: null
            fieldUid: 136d3c61-5e7c-4eb4-afc0-5c78565fbe8b # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f7852fc-9a4e-40a7-9816-dbb286775bf9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f2e4fad-7ce3-4757-abbd-6483c2dc8abe
        userCondition: null
    thumbFieldKey: 'layoutElement:98f0e07e-81da-484f-8190-987af0f739c8'
handle: standardHero
hasTitleField: false
icon: null
name: 'Standard Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
