color: null
fieldLayouts:
  b0e00b72-8d9b-40b3-87a4-efcc1d0bc0ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef403fbe-a0cf-41c3-b22c-76881e7a4fac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d974bf8d-647d-45f3-98be-0733d5e3e1ba # User Guide
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ff5a06e-1c8f-4594-830d-de5bbf507453
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89637c1a-bab7-4e46-9f03-aef99019b870
        userCondition: null
handle: userGuide
hasTitleField: true
icon: person-chalkboard
name: 'User Guide'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
