color: null
fieldLayouts:
  bc2a4d96-e189-4577-9559-d25bf551d2c1:
    cardView:
      - 'layoutElement:d05631c8-4a8b-4de3-8556-fdb8dac2c21f'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:41:59+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionTitle
            instructions: null
            label: 'Section Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d05631c8-4a8b-4de3-8556-fdb8dac2c21f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:41:59+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: sectionsubtitle2
            instructions: null
            label: SectionSubtitle
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e2a1011-236a-4ff2-9867-acac7d531f6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:41:59+00:00'
            elementCondition: null
            fieldUid: 6f74be98-1b1b-470e-a96a-727b01e0b225 # Video Upload
            handle: null
            instructions: null
            label: 'Video Upload'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f452736-a434-4ee7-b2d8-a1bd8f95e768
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56c54d1a-0bc9-493a-a342-789511c65600
        userCondition: null
    thumbFieldKey: 'layoutElement:4f452736-a434-4ee7-b2d8-a1bd8f95e768'
handle: video2
hasTitleField: false
icon: null
name: 'Video (user guide)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
