color: null
fieldLayouts:
  e426ad6b-03b0-4220-8668-3337284b7c5d:
    cardView:
      - 'layoutElement:ac42c12f-111d-4cbb-883c-553898e51e5a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:45:28+00:00'
            elementCondition: null
            fieldUid: 127f0d67-cfaf-4e5d-b3f8-111b7fda6f64 # Padding
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac42c12f-111d-4cbb-883c-553898e51e5a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:45:28+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: videoLink
            instructions: 'YouTube or Vimeo'
            label: 'Video Link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffe24cd2-8cde-4218-aa2a-15b98218f829
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78216433-19bd-4871-aee8-1687783498cd
        userCondition: null
handle: video
hasTitleField: false
icon: null
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
