color: null
fieldLayouts:
  2be8891e-b97f-4d20-8c96-63ee3acef638:
    cardView:
      - 'layoutElement:344c64f5-781b-4fb5-a46b-4429b9f2f253'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-27T16:45:28+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: videoTitle
            instructions: null
            label: 'Video Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 344c64f5-781b-4fb5-a46b-4429b9f2f253
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T16:45:28+00:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: videoId
            instructions: 'i.e. LTRD2wUQ4KY'
            label: 'Video ID'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d461c76-9beb-40da-ae5e-a9d0fe2ded2d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22553107-05a0-4b71-be18-0d3a3d8035b8
        userCondition: null
handle: youtubeVideo
hasTitleField: false
icon: null
name: 'YouTube Video (user guide)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
