fieldLayouts:
  b06de4af-a975-4b6c-8ef4-1c794da71432:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-27T11:37:38-05:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c2cfa525-cf76-4f98-a9aa-5c1053b45a5c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T11:37:38-05:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: altText
            instructions: null
            label: 'Alt Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 294cd7dd-e705-4c7e-8730-ef3c8e6ef66f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-27T11:37:38-05:00'
            elementCondition: null
            fieldUid: c161a9a5-2cf6-4cc3-b0d8-3c8a30395dde # Input
            handle: caption
            instructions: null
            label: Caption
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f87d31c-0e72-4d32-a0ea-c95a5c987e2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 454bf547-c45d-41e0-9375-29df94751d21
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
