columnSuffix: udcdccbn
contentColumnType: text
fieldGroup: ef8cc244-dfa8-41b1-945d-cb673ae71824 # Common
handle: summary
instructions: null
name: Summary
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 70f5d47b-4830-4d51-95fe-bc0f7ccc0670 # Uploads
  ckeConfig: 12f17257-6f1c-4e4c-837e-17ad76241a60 # Site
  columnType: text
  defaultTransform: ''
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
