columnSuffix: ybnmlxai
contentColumnType: text
fieldGroup: ef8cc244-dfa8-41b1-945d-cb673ae71824 # Common
handle: text
instructions: null
name: Text
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 3e09420e-30db-49dd-9520-4775f6667303 # Site Basic
  columnType: text
  defaultTransform: ''
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
