field: 8c583e9a-a56d-486d-8550-e7eae61c8088 # Slides
fieldLayouts:
  67089895-31a3-4dbf-ad4b-7d5cf2c9c385:
    tabs:
      -
        elements:
          -
            fieldUid: d5f8da04-ca55-4c9f-8605-e7f8779e82b8 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51b6bdd2-3479-42db-92bd-f2fb2fb27b63
            warning: null
            width: 100
          -
            fieldUid: 01313804-5d1a-410f-9da8-42ea30ae231d # Slide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a19baf0-3870-4179-836b-f7624be7c6c4
            warning: null
            width: 100
          -
            fieldUid: 8491df26-ac74-440e-8ce9-403654b8ce98 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a04ae6dc-b7fa-46dd-859e-dcff16d29d36
            warning: null
            width: 100
          -
            fieldUid: 59621bb5-03e8-481a-b377-5e08b5a79c12 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51097e95-fc51-4969-82d6-d06ff5a1f646
            warning: null
            width: 100
        name: Content
        uid: 4d5d1e3c-1e1b-4f04-9ca0-0d09f84d1a6c
fields:
  8491df26-ac74-440e-8ce9-403654b8ce98: # Copy
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 3e09420e-30db-49dd-9520-4775f6667303 # Site Basic
      columnType: text
      defaultTransform: ''
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
    translationKeyFormat: null
    translationMethod: site
    type: craft\ckeditor\Field
  59621bb5-03e8-481a-b377-5e08b5a79c12: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: 'Learn more'
      enableAllLinkTypes: false
      enableAriaLabel: true
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
  01313804-5d1a-410f-9da8-42ea30ae231d: # Slide Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: null
    name: 'Slide Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  d5f8da04-ca55-4c9f-8605-e7f8779e82b8: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      defaultUploadLocationSubpath: hero
      localizeRelations: true
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
      restrictedLocationSubpath: hero
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
