description: null
handle: siteAdmin
name: 'Site Admin'
permissions:
  - accesscp
  - accessplugin-seomatic
  - accessplugin-usermanual
  - 'assignusergroup:0878c4de-b946-4c8e-bcce-fe18cd77a73e' # Site Admin
  - 'createentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'createentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'createfolders:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'createfolders:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'deleteassets:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'deleteassets:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'deleteentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'deleteentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'deletepeerassets:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'deletepeerassets:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'deletepeerentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'deletepeerentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'deletepeerentrydrafts:29d88d99-dd38-43f6-9ac5-3438833c75ba' # Error 404
  - 'deletepeerentrydrafts:408314ae-e32d-471b-a729-25f4ce759ac4' # Notice Bar
  - 'deletepeerentrydrafts:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'deletepeerentrydrafts:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'editglobalset:415a954c-eb55-4533-9ffd-64b3eade9469' # Fallback
  - 'editimages:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'editimages:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'editpeerimages:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'editpeerimages:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'editsite:1a78d395-d81a-4b77-8da7-30a49123bbee' # English
  - 'editsite:b9fdef79-5b63-4932-a9aa-8d18f937e6d9' # Fran√ßais
  - 'replacefiles:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'replacefiles:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'replacepeerfiles:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'replacepeerfiles:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'saveassets:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'saveassets:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'saveentries:29d88d99-dd38-43f6-9ac5-3438833c75ba' # Error 404
  - 'saveentries:408314ae-e32d-471b-a729-25f4ce759ac4' # Notice Bar
  - 'saveentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'saveentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'savepeerassets:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'savepeerassets:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'savepeerentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'savepeerentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'savepeerentrydrafts:29d88d99-dd38-43f6-9ac5-3438833c75ba' # Error 404
  - 'savepeerentrydrafts:408314ae-e32d-471b-a729-25f4ce759ac4' # Notice Bar
  - 'savepeerentrydrafts:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'savepeerentrydrafts:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'seomatic:content-meta'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'seomatic:tracking-scripts'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts:gtag'
  - 'utility:asset-indexes'
  - 'utility:db-backup'
  - 'utility:system-report'
  - 'viewassets:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'viewassets:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'viewentries:29d88d99-dd38-43f6-9ac5-3438833c75ba' # Error 404
  - 'viewentries:408314ae-e32d-471b-a729-25f4ce759ac4' # Notice Bar
  - 'viewentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'viewentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'viewpeerassets:70f5d47b-4830-4d51-95fe-bc0f7ccc0670' # Uploads
  - 'viewpeerassets:d19b4314-0267-4e95-9e63-2462a334eea1' # User Guide
  - 'viewpeerentries:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'viewpeerentries:9c12e5ad-18e9-498f-bf50-489513409007' # News
  - 'viewpeerentrydrafts:29d88d99-dd38-43f6-9ac5-3438833c75ba' # Error 404
  - 'viewpeerentrydrafts:408314ae-e32d-471b-a729-25f4ce759ac4' # Notice Bar
  - 'viewpeerentrydrafts:666b31c2-d6d5-4e80-b9aa-f57b66d5b54a' # Pages
  - 'viewpeerentrydrafts:9c12e5ad-18e9-498f-bf50-489513409007' # News
